version: "3"
services:
  postgresql:
    image: postgres:12.2
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: secret
    volumes:
      - "./data:/var/lib/postgresql/data"
  redmine:
    depends_on:
      - postgresql
    image: redmine:4.1.1
    environment:
      REDMINE_DB_POSTGRES: postgresql
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: secret
    ports:
      - "3000:3000"

