apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:12.2
          ports:
          - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: redmine
            - name: POSTGRES_PASSWORD
              value: secret
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
